
lvm:
  # This one you should change
  devicePattern: /dev/nvme[0-9]n[0-9]

  # these are primariliy for testing purposes
  vgName: csi-lvm
  driverName: lvm.csi.metal-stack.io
  storageClassStub: csi-lvm

pluginImage:
  repository: metalstack/lvmplugin
  tag: v0.4.1
  pullPolicy: IfNotPresent

provisionerImage:
  repository: metalstack/csi-lvmplugin-provisioner
  tag: v0.4.1
  pullPolicy: IfNotPresent

rbac:
  create: true
  pspEnabled: true

kubernetes:
  kubeletPath: /var/lib/kubelet

attacher:
  image: k8s.gcr.io/sig-storage/csi-attacher:v3.4.0

livenessprobe:
  image: k8s.gcr.io/sig-storage/livenessprobe:v2.6.0

provisioner:
  image: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0

registrar:
  image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0

resizer:
  image: k8s.gcr.io/sig-storage/csi-resizer:v1.4.0

storageClasses:
  linear:
    enabled: true
    additionalAnnotations: []
    # this might be used to mark one of the StorageClasses as default:
    # storageclass.kubernetes.io/is-default-class: "true"
  striped:
    enabled: true
    additionalAnnotations: []
  mirror:
    enabled: true
    additionalAnnotations: []
